---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ansibledemo1021212.cloudtest1234
  description: ansible
  tags:
    - ansible
    - collection
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: test-rhaap-1/ansibledemo10234
  links:
    - url: https://devspaces.apps.ansible-rhdh-dev.testing.ansible.com/#https://github.com/test-rhaap-1/ansibledemo10234
      title: Open Ansible project in OpenShift Dev Spaces
      icon: web
spec:
  type: collection-project
  lifecycle: production
  owner: user:default/ganeshrn
